name: torchcenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16=py39haa95532_0
  - aom=3.6.1=h63175ca_0
  - arrow=1.2.3=py39haa95532_1
  - astroid=2.14.2=py39haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=23.1.0=py39haa95532_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py39h2bbff1b_1
  - beautifulsoup4=4.12.3=py39haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.4.2=py39haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6c2663c_0
  - boruta_py=0.3=pyhd8ed1ab_1
  - bottleneck=1.3.7=py39h9128911_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py39hd77b12b_8
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.16.0=py39h2bbff1b_1
  - cfitsio=3.470=h0af3d06_7
  - chardet=4.0.0=py39haa95532_1003
  - charls=2.2.0=h39d44d4_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py39haa95532_0
  - cloudpickle=2.2.1=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - contourpy=1.2.0=py39h59b6b97_0
  - cookiecutter=2.6.0=py39haa95532_0
  - cryptography=42.0.5=py39h89fc84f_1
  - cuda-cccl=12.5.39=0
  - cuda-cccl_win-64=12.5.39=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-opencl-dev=12.5.39=0
  - cuda-profiler-api=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py39haa95532_0
  - docstring-to-markdown=0.11=py39haa95532_0
  - docutils=0.18.1=py39haa95532_3
  - exceptiongroup=1.2.0=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h63175ca_0
  - faiss=1.9.0=py39hc157776_0_cpu
  - ffmpeg=5.1.2=gpl_h8bb4bc8_112
  - filelock=3.13.1=py39haa95532_0
  - flake8=7.0.0=py39haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py39h2bbff1b_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.12.1=ha860e81_0
  - gettext=0.22.5=h5728263_2
  - gettext-tools=0.22.5=h7d00a51_2
  - giflib=5.2.2=h64bf75a_0
  - glib=2.80.2=h0df6a38_0
  - glib-tools=2.80.2=h2f9d560_0
  - gmpy2=2.1.2=py39h7f96b67_0
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - harfbuzz=6.0.0=he256f1b_0
  - icu=70.1=h0e60522_0
  - idna=3.7=py39haa95532_0
  - imagecodecs=2023.1.23=py39h6c6a46e_0
  - imageio=2.34.2=pyh12aca89_0
  - imagesize=1.4.1=py39haa95532_0
  - imbalanced-learn=0.12.3=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=py39haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py39haa95532_0
  - inflection=0.5.1=py39haa95532_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.28.0=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - isort=5.13.2=py39haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jasper=2.0.33=hc2e4405_1
  - jedi=0.19.1=py39haa95532_0
  - jellyfish=1.0.1=py39h36a85e1_0
  - jinja2=3.1.4=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.19.2=py39haa95532_0
  - jsonschema-specifications=2023.7.1=py39haa95532_0
  - jupyter_client=8.6.0=py39haa95532_0
  - jupyter_core=5.7.2=py39haa95532_0
  - jupyterlab_pygments=0.2.2=py39haa95532_0
  - keyring=24.3.1=py39haa95532_0
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lazy-object-proxy=1.10.0=py39h2bbff1b_0
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_2
  - libasprintf-devel=0.22.5=h5728263_2
  - libavif=0.11.1=h2bbff1b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang13=15.0.7=default_hf64faad_5
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.6.82=0
  - libcurand-dev=10.3.6.82=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.6.2=h63175ca_0
  - libfaiss=1.9.0=h3a9ed07_0_cpu
  - libfaiss-avx2=1.7.4=h1234567_0_cpu
  - libffi=3.4.2=h8ffe710_5
  - libgettextpo=0.22.5=h5728263_2
  - libgettextpo-devel=0.22.5=h5728263_2
  - libglib=2.80.2=h0df6a38_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_2
  - libintl-devel=0.22.5=h5728263_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - liblapacke=3.9.0=5_hd5c7e75_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libogg=1.3.5=h2466b09_0
  - libopencv=4.7.0=py39ha9d37a1_1
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libprotobuf=3.21.12=h12be248_2
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libsqlite=3.46.0=h2466b09_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.12.7=h283a6d9_1
  - libzlib=1.2.13=h2466b09_6
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=2.2.0=py39haa95532_1
  - markupsafe=2.1.3=py39h2bbff1b_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py39haa95532_0
  - mistune=2.0.4=py39haa95532_0
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - more-itertools=10.1.0=py39haa95532_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - msys2-conda-epoch=20160418=1
  - mypy_extensions=1.0.0=py39haa95532_0
  - nbclient=0.8.0=py39haa95532_0
  - nbconvert=7.10.0=py39haa95532_0
  - nbformat=5.9.2=py39haa95532_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.8.4=py39h5b0cc5e_0
  - numpydoc=1.7.0=py39haa95532_0
  - opencv=4.7.0=py39hcbf5309_1
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.4.0=h4afccc4_2
  - openssl=3.5.0=ha4e3fda_1
  - packaging=24.1=py39haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py39haa95532_0
  - pcre2=10.43=h17e33f8_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py39h827c3e9_0
  - pip=24.0=py39haa95532_0
  - pixman=0.43.4=h63175ca_0
  - platformdirs=3.10.0=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - ply=3.11=py39haa95532_0
  - prompt-toolkit=3.0.43=py39haa95532_0
  - psutil=5.9.0=py39h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.7.0=py39h00e5391_1
  - pycodestyle=2.11.1=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py39haa95532_0
  - pyflakes=3.2.0=py39haa95532_0
  - pygments=2.15.1=py39haa95532_1
  - pylint=2.16.2=py39haa95532_0
  - pylint-venv=3.0.3=py39haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py39h8cc25b3_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.10=py39hd77b12b_0
  - pyqt5-sip=12.13.0=py39h2bbff1b_0
  - pyqtwebengine=5.15.10=py39hd77b12b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.19=h1aa4202_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-fastjsonschema=2.16.2=py39haa95532_0
  - python-lsp-black=2.0.0=py39haa95532_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.10.0=py39haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.6=py39haa95532_0
  - pytorch=2.3.1=py3.9_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39haa95532_0
  - pywavelets=1.6.0=py39h4b0a98a_0
  - pywin32=305=py39h2bbff1b_0
  - pywin32-ctypes=0.2.2=py39haa95532_0
  - pyyaml=6.0.1=py39h2bbff1b_0
  - pyzmq=25.1.2=py39hd77b12b_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py39haa95532_0
  - qt-main=5.15.8=h720456b_6
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.2.2=py39haa95532_0
  - qtconsole=5.5.1=py39haa95532_0
  - qtpy=2.4.1=py39haa95532_0
  - qudida=0.0.4=pyhd8ed1ab_0
  - referencing=0.30.2=py39haa95532_0
  - requests=2.32.2=py39haa95532_0
  - rich=13.7.1=py39haa95532_0
  - rope=1.12.0=py39haa95532_0
  - rpds-py=0.10.6=py39h062c2fa_0
  - rtree=1.0.1=py39h2eaa2aa_0
  - scikit-image=0.24.0=py39h2366fc2_1
  - setuptools=69.5.1=py39haa95532_0
  - sip=6.7.12=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h23299a8_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39haa95532_0
  - sphinx=7.3.7=py39h827c3e9_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py39haa95532_0
  - spyder=5.5.1=py39haa95532_3
  - spyder-kernels=2.5.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=1.4.1=h63175ca_0
  - sympy=1.12=py39haa95532_0
  - tabulate=0.9.0=py39haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2023.8.12=pyhd8ed1ab_0
  - tinycss2=1.2.1=py39haa95532_0
  - tomli=2.0.1=py39haa95532_0
  - tomlkit=0.11.1=py39haa95532_0
  - tornado=6.4.1=py39h827c3e9_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.11.0=py39haa95532_0
  - typing_extensions=4.11.0=py39haa95532_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ujson=5.10.0=py39h5da7b33_0
  - unicodedata2=15.1.0=py39h2bbff1b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=2.2.2=py39haa95532_0
  - vc=14.2=h2eaa2aa_4
  - vc14_runtime=14.40.33810=ha82c5b3_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - watchdog=4.0.1=py39haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - whatthepatch=1.0.2=py39haa95532_0
  - wheel=0.43.0=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wrapt=1.14.1=py39h2bbff1b_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yapf=0.40.2=py39haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=1.0.1=he0c23c2_1
  - zipp=3.17.0=py39haa95532_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.5=hd43e919_2
  - pip:
      - absl-py==2.1.0
      - accelerate==1.10.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.16
      - albumentations==1.4.14
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - blinker==1.8.2
      - boruta==0.4.3
      - captum==0.7.0
      - category-encoders==2.6.3
      - clean-fid==0.1.35
      - cython==3.0.10
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==4.1.1
      - deprecation==2.1.0
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - frozenlist==1.4.1
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.14.0
      - hiddenlayer==0.3
      - huggingface-hub==0.35.0
      - imutils==0.5.4
      - intel-openmp==2021.4.0
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.11
      - kaleido==0.2.1
      - keras==3.10.0
      - libclang==18.1.1
      - lightgbm==4.4.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - markdown==3.7
      - matplotlib==3.7.5
      - mkl==2021.4.0
      - ml-dtypes==0.5.1
      - mrmr-selection==0.2.8
      - multidict==6.1.0
      - multiprocess==0.70.16
      - namex==0.1.0
      - netron==8.6.9
      - nibabel==5.3.2
      - numba==0.60.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - onnx==1.19.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - orjson==3.10.6
      - pandas==2.1.4
      - patsy==0.5.6
      - plotly==5.22.0
      - plotly-resampler==0.10.0
      - pmdarima==2.0.4
      - polars==1.2.1
      - protobuf==5.28.0
      - pyarrow==21.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydicom==2.4.4
      - pykwalify==1.8.0
      - pynndescent==0.5.13
      - pyod==2.0.1
      - pyradiomics==3.1.0
      - pytesseract==0.3.13
      - python-graphviz==0.21
      - pytorch-lightning==2.4.0
      - regex==2024.9.11
      - retrying==1.3.4
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.4.3
      - schemdraw==0.15
      - scikit-base==0.7.8
      - scikit-learn==1.4.2
      - scikit-plot==0.3.7
      - scipy==1.11.4
      - seaborn==0.13.2
      - simpleitk==2.4.1
      - sktime==0.26.0
      - statsmodels==0.14.2
      - tbats==1.1.3
      - tbb==2021.13.0
      - tenacity==8.5.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tokenizers==0.14.1
      - torchaudio==2.3.1
      - torchmetrics==1.4.1
      - torchview==0.2.7
      - torchvision==0.18.1
      - transformers==4.34.1
      - tsdownsample==0.1.3
      - umap-learn==0.5.7
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xxhash==3.4.1
      - yarl==1.11.1
      - yellowbrick==1.5
prefix: C:\Users\Anaconda3\envs\torchcenv
